version: '3'

services:
  nginx: 
    image: nginx:1.16
    ports: 
      - "8000:8000" 
    volumes: 
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/log:/var/log/nginx
      - ./static:/static
    depends_on: 
      - python 
    environment: 
      TZ: 'Asia/Tokyo'

  db: 
    image: mysql:5.7
    ports: 
      - "3306:3306" 
    environment: 
      MYSQL_ROOT_PASSWORD: rootpass
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d 
      - ./backup:/var/lib/backup
    command: --innodb-use-native-aio=0

  python:
    build: ./python
    command: uwsgi --socket :8001 --module portfolio.wsgi --py-autoreload 1 --logto /tmp/mylog.log
    volumes:
      - ./src:/code
      - ./static:/static
    expose: 
      - "8001"
    depends_on: 
      - db
    environment:
      TZ: 'Asia/Tokyo'
